sync:
  name: Data Sync
  icon: sync
  link: /services/data-sync/
  description: Add realtime data synchronization and offline capabilities to your mobile app
  features:
    - Use GraphQL to design the APIs for your mobile app
    - Add real time data synchronisation to your mobile app
    - Allow your mobile app to work offline
    - Easily resolve conflicts with the flexible conflict resolution strategies
    - Support authentication and authorization using the Identity Management service or choice of your own
    - Great observability through the AeroGear Mobile Metrics Service
    - Track all actions with audit logs
  documentation: https://docs.aerogear.org/aerogear/latest/data-sync.html
  github: https://github.com/aerogear/voyager-server/

identity: 
  name: Identity Management
  icon: account_circle
  link: /services/identity-management/
  description: Add authentication and authorization to your mobile app
  features:
    - Secure your mobile app using the industry standard OpenID Connect protocol
    - Add access control to your app based on user’s group membership
    - Easily implement SSO, multi factor authentication and Social Login support
    - Back end support for identity brokering and user federation
  documentation: https://docs.aerogear.org/aerogear/latest/identity-management.html
  github: https://github.com/aerogearcatalog/keycloak-apb/

push:
  name: Push Notifications
  icon: notifications_active
  link: /services/push/
  description: Send native push notifications to different mobile operating systems 
  features:
    - Code once and send push notifications to iOS and Android
    - Send push notifications to defined groups
    - Send push notifications to different variants of a mobile app
    - Send push notifications from different back-end apps to the same mobile app
  documentation: https://docs.aerogear.org/aerogear/latest/push-notifications.html
  github: https://github.com/aerogearcatalog/unifiedpush-apb/

metrics:
  name: Mobile Metrics
  icon: insert_chart
  link: /services/metrics/
  description: Gather metrics on mobile apps, device versions, device security checks and back-end mobile service usage
  features: 
    - Monitor usage by version of mobile app, platform and SDK
    - Monitor interactions with the Identity Management service
  documentation: https://docs.aerogear.org/aerogear/latest/mobile-metrics.html
  github: https://github.com/aerogearcatalog/metrics-apb/

ci:
  name: Mobile CI/CD
  icon: build
  link: /services/mobile-ci-cd/
  description: Automate the building of your native and hybrid mobile app for both Android and iOS
  features: 
    - Leverage your Jenkins expertise to manage and automate mobile builds
    - Containerised builds on OpenShift for Android
    - Support for integrating OSX as build slaves for iOS builds
  documentation: https://docs.aerogear.org/aerogear/latest/mobile-cicd.html
  github: https://github.com/aerogearcatalog/aerogear-digger-apb

device-security:
  name: Device Security
  icon: security
  link: /services/device-security/
  description: Easily configure and manage device security, and trust checks for your mobile app
  features: 
    - Perform a range of device trust checks on the mobile device, such as checking if the device is rooted, and allows you take proactive action based on the results
    - Distribute SSL certificates with a mobile app to create a direct chain of trust (certificate pinning) for Android
  documentation: https://docs.aerogear.org/aerogear/latest/device-security.html
  github: 

app-security:
  name: Application Security
  icon: lock
  link: /services/app-security/
  description: Easily configure and manage application security 
  features: 
    - Allows you to connect to the bound mobile security service on OpenShift 
    - Can be use by a security administrator to enable or disable applications
    - Returns a message from the mobile security service which can be used by a developer to inform a user that the application has been disabled.
  documentation: https://docs.aerogear.org/aerogear/latest/app-security.html
  github: 
